namespace: voting-dev

imagePullSecrets: []

image:
  tag: "ab5d39a"

vote:
  replicaCount: 1
  service:
    type: ClusterIP

result:
  replicaCount: 1
  service:
    type: ClusterIP

worker:
  replicaCount: 1

postgres:
  storage: 1Gi
  storageClassName: gp2
