apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.result.service.type }}
  selector:
    app: result
  ports:
    - port: {{ .Values.result.service.port }}
      targetPort: {{ .Values.result.service.targetPort }}
