apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.result.replicaCount }}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: result
          image: "{{ .Values.image.registry }}/{{ .Values.result.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: {{ .Values.result.env.port | quote }}
          envFrom:
            - secretRef:
                name: {{ required "postgres.existingSecret is required" .Values.postgres.existingSecret }}
