apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.vote.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: vote
          image: "{{ .Values.image.registry }}/{{ .Values.vote.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: REDIS
              value: redis
