apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
      annotations:
        voting.devsecops/release-id: {{ .Values.release.id | quote }}
    spec:
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.image.registry }}/{{ .Values.worker.image.repository }}@{{ .Values.worker.image.digest }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ required "postgres.existingSecret is required" .Values.postgres.existingSecret }}
