name: CI - DevSecOps Modular

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  secret-scan:
    name: Secret scan
    uses: ./.github/workflows/reuseable-secret-scan.yml
    secrets: inherit

  source-scan:
    name: Source Vulnerability Scan
    uses: ./.github/workflows/reuseable-source-scan.yml

  code-quality:
    name: Code Quality Scan
    uses: ./.github/workflows/reuseable-code-quality.yml
    secrets: inherit

  docker-ci:
    name: Docker Build, Image Scan and Compose Test
    uses: ./.github/workflows/reuseable-docker-ci.yml
    needs:
      - secret-scan
      - source-scan
  
  helm-validate:
    name: Helm validate
    uses: ./.github/workflows/reuseable-helm-validate.yml