name: CI - DevSecOps Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write

jobs:
  devsecops-ci:
    name: Build, test and security scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Show repository structure
        run: |
          pwd
          ls -la
          find . -maxdepth 2 -type f | sort

      - name: Check Docker version
        run: |
          docker --version
          docker compose version

      - name: Run Gitleaks secret scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"
          format: table

      - name: Validate docker-compose.yml
        run: docker compose config

      - name: Build Docker images
        run: docker compose build

      - name: Scan vote image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: voting-vote:local
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"
          format: table

      - name: Scan result image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: voting-result:local
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"
          format: table

      - name: Scan worker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: voting-worker:local
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"
          format: table

      - name: Start services
        run: docker compose up -d

      - name: Wait for services
        run: |
          sleep 20
          docker compose ps

      - name: Test vote service
        run: curl -f http://localhost:5000 || exit 1

      - name: Test result service
        run: curl -f http://localhost:5001 || exit 1

      - name: Configure AWS credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS identity
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: aws sts get-caller-identity

      - name: Show logs
        if: always()
        run: docker compose logs --no-color

      - name: Stop services
        if: always()
        run: docker compose down -v
