name: Reuseable - Code Quality

on:
  workflow_call:

permissions:
  contents: read

jobs:
  sonarcloud:
    name: SonarCloud Code Quality Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: SonarCloud code quality scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io