name: Reuseable Vulnerability Scan

on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  trivy-fs:
    name: Trivy Filesystem scan
    runs-on: ubuntu:latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"
          format: table
